INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (1, NULL, GETDATE(), 2940.46, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (2, 3, GETDATE(), 19522.11, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (3, NULL, GETDATE(), 1171.21, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (4, NULL, GETDATE(), 4384.33, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (5, 6, GETDATE(), 11250.78, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (6, NULL, GETDATE(), 885.27, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (7, NULL, GETDATE(), 4644.12, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (8, 9, GETDATE(), 23901.84, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (9, NULL, GETDATE(), 831.73, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (10, NULL, GETDATE(), 2616.75, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (11, 12, GETDATE(), 6410.1, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (12, NULL, GETDATE(), 652.99, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (13, NULL, GETDATE(), 4938.39, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (14, 15, GETDATE(), 10988.79, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (15, NULL, GETDATE(), 1122.88, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (16, NULL, GETDATE(), 2940.01, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (17, 18, GETDATE(), 6066.71, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (18, NULL, GETDATE(), 530.15, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (19, NULL, GETDATE(), 3079.38, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (20, 1, GETDATE(), 19062.54, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (21, NULL, GETDATE(), 1160.75, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (22, NULL, GETDATE(), 4421.43, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (23, 4, GETDATE(), 21385.8, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (24, NULL, GETDATE(), 1242.19, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (25, NULL, GETDATE(), 3010.84, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (26, 7, GETDATE(), 5144.21, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (27, NULL, GETDATE(), 1332.08, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (28, NULL, GETDATE(), 3602.97, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (29, 10, GETDATE(), 8870.43, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (30, NULL, GETDATE(), 117.5, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (31, NULL, GETDATE(), 2869.38, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (32, 13, GETDATE(), 6368.6, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (33, NULL, GETDATE(), 874.3, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (34, NULL, GETDATE(), 2961.77, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (35, 16, GETDATE(), 21273.75, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (36, NULL, GETDATE(), 505.23, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (37, NULL, GETDATE(), 1533.43, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (38, 19, GETDATE(), 5502.99, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (39, NULL, GETDATE(), 348.18, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (40, NULL, GETDATE(), 4421.49, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (41, 2, GETDATE(), 8690.67, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (42, NULL, GETDATE(), 678.09, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (43, NULL, GETDATE(), 2903.21, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (44, 5, GETDATE(), 24407.59, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (45, NULL, GETDATE(), 566.64, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (46, NULL, GETDATE(), 4016.31, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (47, 8, GETDATE(), 22701.74, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (48, NULL, GETDATE(), 910.12, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (49, NULL, GETDATE(), 1214.72, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (50, 11, GETDATE(), 8414.43, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (51, NULL, GETDATE(), 1340.74, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (52, NULL, GETDATE(), 1636.47, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (53, 14, GETDATE(), 8802.97, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (54, NULL, GETDATE(), 1171.88, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (55, NULL, GETDATE(), 2611.55, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (56, 17, GETDATE(), 22897.9, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (57, NULL, GETDATE(), 1028.3, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (58, NULL, GETDATE(), 1105.19, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (59, 20, GETDATE(), 6683.34, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (60, NULL, GETDATE(), 144.01, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (61, NULL, GETDATE(), 2295.1, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (62, 3, GETDATE(), 16294.72, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (63, NULL, GETDATE(), 1004.39, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (64, NULL, GETDATE(), 2538.01, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (65, 6, GETDATE(), 17585.91, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (66, NULL, GETDATE(), 509.67, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (67, NULL, GETDATE(), 1509.19, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (68, 9, GETDATE(), 11483.11, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (69, NULL, GETDATE(), 324.82, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (70, NULL, GETDATE(), 3847.67, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (71, 12, GETDATE(), 20393.14, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (72, NULL, GETDATE(), 1028.37, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (73, NULL, GETDATE(), 1362.81, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (74, 15, GETDATE(), 7738.39, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (75, NULL, GETDATE(), 107.15, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (76, NULL, GETDATE(), 1221.19, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (77, 18, GETDATE(), 15536.8, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (78, NULL, GETDATE(), 1260.9, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (79, NULL, GETDATE(), 3462.57, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (80, 1, GETDATE(), 15918.46, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (81, NULL, GETDATE(), 1326.36, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (82, NULL, GETDATE(), 3147.55, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (83, 4, GETDATE(), 14900.44, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (84, NULL, GETDATE(), 166.6, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (85, NULL, GETDATE(), 4941.62, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (86, 7, GETDATE(), 11357.61, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (87, NULL, GETDATE(), 741.56, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (88, NULL, GETDATE(), 4972.89, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (89, 10, GETDATE(), 22863.11, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (90, NULL, GETDATE(), 1094.45, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (91, NULL, GETDATE(), 2077.57, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (92, 13, GETDATE(), 14062.91, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (93, NULL, GETDATE(), 1343.24, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (94, NULL, GETDATE(), 556.76, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (95, 16, GETDATE(), 21594.75, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (96, NULL, GETDATE(), 1359.09, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (97, NULL, GETDATE(), 3328.98, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (98, 19, GETDATE(), 15954.65, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (99, NULL, GETDATE(), 410.74, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (100, NULL, GETDATE(), 781.96, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (101, 2, GETDATE(), 12271.72, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (102, NULL, GETDATE(), 621.68, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (103, NULL, GETDATE(), 1840.08, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (104, 5, GETDATE(), 24358.47, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (105, NULL, GETDATE(), 447.81, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (106, NULL, GETDATE(), 3236.17, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (107, 8, GETDATE(), 5561.94, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (108, NULL, GETDATE(), 799.8, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (109, NULL, GETDATE(), 1772.16, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (110, 11, GETDATE(), 8172.61, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (111, NULL, GETDATE(), 1264.18, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (112, NULL, GETDATE(), 4261.46, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (113, 14, GETDATE(), 24895.73, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (114, NULL, GETDATE(), 1460.39, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (115, NULL, GETDATE(), 3775.39, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (116, 17, GETDATE(), 9263.01, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (117, NULL, GETDATE(), 213.54, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (118, NULL, GETDATE(), 2586.1, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (119, 20, GETDATE(), 6110.65, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (120, NULL, GETDATE(), 1272.51, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (121, NULL, GETDATE(), 4084.69, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (122, 3, GETDATE(), 9537.93, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (123, NULL, GETDATE(), 158.07, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (124, NULL, GETDATE(), 1978.83, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (125, 6, GETDATE(), 12172.87, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (126, NULL, GETDATE(), 686.7, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (127, NULL, GETDATE(), 1795.14, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (128, 9, GETDATE(), 8045.9, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (129, NULL, GETDATE(), 705.56, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (130, NULL, GETDATE(), 4916.61, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (131, 12, GETDATE(), 8053.9, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (132, NULL, GETDATE(), 511.41, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (133, NULL, GETDATE(), 4239.14, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (134, 15, GETDATE(), 13755.74, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (135, NULL, GETDATE(), 386.1, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (136, NULL, GETDATE(), 4415.81, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (137, 18, GETDATE(), 18568.83, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (138, NULL, GETDATE(), 466.89, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (139, NULL, GETDATE(), 4214.02, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (140, 1, GETDATE(), 8129.84, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (141, NULL, GETDATE(), 1311.11, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (142, NULL, GETDATE(), 2647.04, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (143, 4, GETDATE(), 13099.3, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (144, NULL, GETDATE(), 707.08, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (145, NULL, GETDATE(), 2010.0, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (146, 7, GETDATE(), 24553.13, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (147, NULL, GETDATE(), 280.23, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (148, NULL, GETDATE(), 1553.67, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (149, 10, GETDATE(), 19340.3, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (150, NULL, GETDATE(), 589.76, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (151, NULL, GETDATE(), 1391.56, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (152, 13, GETDATE(), 17039.17, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (153, NULL, GETDATE(), 1258.99, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (154, NULL, GETDATE(), 3871.0, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (155, 16, GETDATE(), 22243.24, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (156, NULL, GETDATE(), 794.58, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (157, NULL, GETDATE(), 2745.37, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (158, 19, GETDATE(), 11002.47, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (159, NULL, GETDATE(), 1065.61, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (160, NULL, GETDATE(), 3063.96, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (161, 2, GETDATE(), 8861.42, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (162, NULL, GETDATE(), 956.35, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (163, NULL, GETDATE(), 847.17, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (164, 5, GETDATE(), 5946.67, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (165, NULL, GETDATE(), 1037.84, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (166, NULL, GETDATE(), 1129.15, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (167, 8, GETDATE(), 20652.28, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (168, NULL, GETDATE(), 630.15, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (169, NULL, GETDATE(), 3234.08, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (170, 11, GETDATE(), 17444.88, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (171, NULL, GETDATE(), 395.33, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (172, NULL, GETDATE(), 3834.68, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (173, 14, GETDATE(), 17674.38, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (174, NULL, GETDATE(), 1423.55, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (175, NULL, GETDATE(), 4793.39, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (176, 17, GETDATE(), 14287.77, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (177, NULL, GETDATE(), 443.28, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (178, NULL, GETDATE(), 747.15, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (179, 20, GETDATE(), 18573.68, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (180, NULL, GETDATE(), 757.62, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (181, NULL, GETDATE(), 1145.73, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (182, 3, GETDATE(), 12145.12, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (183, NULL, GETDATE(), 790.53, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (184, NULL, GETDATE(), 606.13, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (185, 6, GETDATE(), 6185.66, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (186, NULL, GETDATE(), 155.35, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (187, NULL, GETDATE(), 3956.42, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (188, 9, GETDATE(), 9084.3, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (189, NULL, GETDATE(), 896.35, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (190, NULL, GETDATE(), 1978.84, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (191, 12, GETDATE(), 19761.82, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (192, NULL, GETDATE(), 261.25, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (193, NULL, GETDATE(), 3210.36, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (194, 15, GETDATE(), 23432.73, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (195, NULL, GETDATE(), 144.82, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (196, NULL, GETDATE(), 4133.15, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (197, 18, GETDATE(), 19800.47, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (198, NULL, GETDATE(), 1242.67, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (199, NULL, GETDATE(), 2519.98, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (200, 1, GETDATE(), 9006.54, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (201, NULL, GETDATE(), 1021.65, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (202, NULL, GETDATE(), 1575.97, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (203, 4, GETDATE(), 11244.56, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (204, NULL, GETDATE(), 772.19, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (205, NULL, GETDATE(), 2072.33, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (206, 7, GETDATE(), 22999.55, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (207, NULL, GETDATE(), 711.49, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (208, NULL, GETDATE(), 2415.76, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (209, 10, GETDATE(), 8104.41, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (210, NULL, GETDATE(), 833.52, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (211, NULL, GETDATE(), 2539.79, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (212, 13, GETDATE(), 23995.09, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (213, NULL, GETDATE(), 1113.81, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (214, NULL, GETDATE(), 4739.88, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (215, 16, GETDATE(), 9555.35, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (216, NULL, GETDATE(), 592.49, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (217, NULL, GETDATE(), 3523.75, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (218, 19, GETDATE(), 9456.27, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (219, NULL, GETDATE(), 371.21, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (220, NULL, GETDATE(), 3874.66, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (221, 2, GETDATE(), 15444.5, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (222, NULL, GETDATE(), 1292.78, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (223, NULL, GETDATE(), 3069.31, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (224, 5, GETDATE(), 24853.12, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (225, NULL, GETDATE(), 1296.97, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (226, NULL, GETDATE(), 2732.84, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (227, 8, GETDATE(), 8088.93, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (228, NULL, GETDATE(), 1001.91, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (229, NULL, GETDATE(), 837.4, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (230, 11, GETDATE(), 21791.93, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (231, NULL, GETDATE(), 121.4, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (232, NULL, GETDATE(), 4502.38, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (233, 14, GETDATE(), 23241.48, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (234, NULL, GETDATE(), 775.57, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (235, NULL, GETDATE(), 2607.4, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (236, 17, GETDATE(), 18981.53, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (237, NULL, GETDATE(), 1295.82, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (238, NULL, GETDATE(), 4594.18, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (239, 20, GETDATE(), 13827.56, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (240, NULL, GETDATE(), 1139.33, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (241, NULL, GETDATE(), 3656.17, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (242, 3, GETDATE(), 16863.17, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (243, NULL, GETDATE(), 323.63, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (244, NULL, GETDATE(), 1696.95, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (245, 6, GETDATE(), 17510.68, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (246, NULL, GETDATE(), 125.03, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (247, NULL, GETDATE(), 2032.47, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (248, 9, GETDATE(), 9380.47, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (249, NULL, GETDATE(), 1266.33, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (250, NULL, GETDATE(), 1295.74, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (251, 12, GETDATE(), 20180.07, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (252, NULL, GETDATE(), 1175.33, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (253, NULL, GETDATE(), 1518.37, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (254, 15, GETDATE(), 12856.21, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (255, NULL, GETDATE(), 363.75, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (256, NULL, GETDATE(), 1104.17, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (257, 18, GETDATE(), 19523.63, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (258, NULL, GETDATE(), 762.91, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (259, NULL, GETDATE(), 1616.63, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (260, 1, GETDATE(), 21932.2, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (261, NULL, GETDATE(), 1056.26, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (262, NULL, GETDATE(), 3493.01, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (263, 4, GETDATE(), 23966.9, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (264, NULL, GETDATE(), 710.07, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (265, NULL, GETDATE(), 1796.64, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (266, 7, GETDATE(), 10845.59, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (267, NULL, GETDATE(), 999.48, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (268, NULL, GETDATE(), 2526.45, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (269, 10, GETDATE(), 22068.45, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (270, NULL, GETDATE(), 1478.11, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (271, NULL, GETDATE(), 2409.4, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (272, 13, GETDATE(), 13654.96, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (273, NULL, GETDATE(), 761.84, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (274, NULL, GETDATE(), 1026.69, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (275, 16, GETDATE(), 20722.54, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (276, NULL, GETDATE(), 1419.05, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (277, NULL, GETDATE(), 1641.13, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (278, 19, GETDATE(), 20418.15, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (279, NULL, GETDATE(), 474.11, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (280, NULL, GETDATE(), 1867.02, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (281, 2, GETDATE(), 18534.9, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (282, NULL, GETDATE(), 161.0, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (283, NULL, GETDATE(), 3339.79, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (284, 5, GETDATE(), 13563.89, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (285, NULL, GETDATE(), 262.34, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (286, NULL, GETDATE(), 2850.75, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (287, 8, GETDATE(), 13028.27, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (288, NULL, GETDATE(), 759.11, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (289, NULL, GETDATE(), 2871.77, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (290, 11, GETDATE(), 15760.57, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (291, NULL, GETDATE(), 1341.42, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (292, NULL, GETDATE(), 3317.04, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (293, 14, GETDATE(), 16286.79, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (294, NULL, GETDATE(), 425.07, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (295, NULL, GETDATE(), 1954.15, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (296, 17, GETDATE(), 9161.64, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (297, NULL, GETDATE(), 609.94, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (298, NULL, GETDATE(), 3363.86, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (299, 20, GETDATE(), 5701.27, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (300, NULL, GETDATE(), 1064.31, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (301, NULL, GETDATE(), 3039.31, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (302, 3, GETDATE(), 5747.73, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (303, NULL, GETDATE(), 203.54, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (304, NULL, GETDATE(), 3728.49, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (305, 6, GETDATE(), 9100.79, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (306, NULL, GETDATE(), 542.41, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (307, NULL, GETDATE(), 2653.96, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (308, 9, GETDATE(), 6721.98, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (309, NULL, GETDATE(), 1341.56, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (310, NULL, GETDATE(), 2999.32, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (311, 12, GETDATE(), 12100.2, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (312, NULL, GETDATE(), 1116.93, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (313, NULL, GETDATE(), 3857.08, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (314, 15, GETDATE(), 17546.38, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (315, NULL, GETDATE(), 882.85, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (316, NULL, GETDATE(), 4981.77, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (317, 18, GETDATE(), 13434.58, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (318, NULL, GETDATE(), 1222.43, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (319, NULL, GETDATE(), 4156.41, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (320, 1, GETDATE(), 5988.93, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (321, NULL, GETDATE(), 900.26, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (322, NULL, GETDATE(), 1419.51, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (323, 4, GETDATE(), 20645.16, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (324, NULL, GETDATE(), 1263.37, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (325, NULL, GETDATE(), 717.15, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (326, 7, GETDATE(), 14803.72, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (327, NULL, GETDATE(), 1022.11, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (328, NULL, GETDATE(), 2929.43, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (329, 10, GETDATE(), 12953.89, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (330, NULL, GETDATE(), 547.52, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (331, NULL, GETDATE(), 4710.06, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (332, 13, GETDATE(), 11696.62, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (333, NULL, GETDATE(), 1108.86, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (334, NULL, GETDATE(), 917.24, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (335, 16, GETDATE(), 18213.52, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (336, NULL, GETDATE(), 641.49, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (337, NULL, GETDATE(), 2971.58, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (338, 19, GETDATE(), 19279.8, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (339, NULL, GETDATE(), 651.45, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (340, NULL, GETDATE(), 4800.87, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (341, 2, GETDATE(), 8312.49, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (342, NULL, GETDATE(), 1157.31, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (343, NULL, GETDATE(), 1129.23, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (344, 5, GETDATE(), 15701.81, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (345, NULL, GETDATE(), 795.94, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (346, NULL, GETDATE(), 3687.42, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (347, 8, GETDATE(), 18481.65, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (348, NULL, GETDATE(), 1188.37, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (349, NULL, GETDATE(), 3426.29, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (350, 11, GETDATE(), 16196.8, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (351, NULL, GETDATE(), 429.42, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (352, NULL, GETDATE(), 4107.1, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (353, 14, GETDATE(), 18877.11, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (354, NULL, GETDATE(), 831.27, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (355, NULL, GETDATE(), 2170.92, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (356, 17, GETDATE(), 9480.1, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (357, NULL, GETDATE(), 1497.42, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (358, NULL, GETDATE(), 4714.26, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (359, 20, GETDATE(), 23698.73, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (360, NULL, GETDATE(), 1088.7, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (361, NULL, GETDATE(), 2358.71, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (362, 3, GETDATE(), 19679.17, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (363, NULL, GETDATE(), 1137.02, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (364, NULL, GETDATE(), 1507.13, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (365, 6, GETDATE(), 10054.95, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (366, NULL, GETDATE(), 277.62, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (367, NULL, GETDATE(), 2468.49, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (368, 9, GETDATE(), 23633.65, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (369, NULL, GETDATE(), 1039.95, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (370, NULL, GETDATE(), 4555.89, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (371, 12, GETDATE(), 13599.83, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (372, NULL, GETDATE(), 620.91, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (373, NULL, GETDATE(), 987.95, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (374, 15, GETDATE(), 14271.1, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (375, NULL, GETDATE(), 725.64, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (376, NULL, GETDATE(), 1808.05, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (377, 18, GETDATE(), 24505.81, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (378, NULL, GETDATE(), 799.31, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (379, NULL, GETDATE(), 3001.78, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (380, 1, GETDATE(), 18895.6, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (381, NULL, GETDATE(), 1073.39, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (382, NULL, GETDATE(), 646.97, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (383, 4, GETDATE(), 8125.93, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (384, NULL, GETDATE(), 507.05, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (385, NULL, GETDATE(), 2931.94, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (386, 7, GETDATE(), 5466.17, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (387, NULL, GETDATE(), 1415.21, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (388, NULL, GETDATE(), 1073.9, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (389, 10, GETDATE(), 12567.65, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (390, NULL, GETDATE(), 283.96, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (391, NULL, GETDATE(), 4804.03, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (392, 13, GETDATE(), 18265.16, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (393, NULL, GETDATE(), 924.04, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (394, NULL, GETDATE(), 641.74, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (395, 16, GETDATE(), 18949.25, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (396, NULL, GETDATE(), 369.04, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (397, NULL, GETDATE(), 1844.31, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (398, 19, GETDATE(), 10110.52, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (399, NULL, GETDATE(), 791.44, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (400, NULL, GETDATE(), 1130.83, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (401, 2, GETDATE(), 5727.62, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (402, NULL, GETDATE(), 257.85, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (403, NULL, GETDATE(), 4715.84, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (404, 5, GETDATE(), 20865.43, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (405, NULL, GETDATE(), 1269.02, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (406, NULL, GETDATE(), 508.56, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (407, 8, GETDATE(), 5837.05, 'employers remmitance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (408, NULL, GETDATE(), 444.46, 'Mpesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (409, NULL, GETDATE(), 3089.74, 'Bank-transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (410, 11, GETDATE(), 16641.31, 'employers remmitance');
