INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (1, NULL, GETDATE(), 3013.35, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (2, 3, GETDATE(), 16467.11, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (3, NULL, GETDATE(), 119.96, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (4, NULL, GETDATE(), 4757.88, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (5, 6, GETDATE(), 24158.99, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (6, NULL, GETDATE(), 477.7, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (7, NULL, GETDATE(), 1120.81, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (8, 9, GETDATE(), 7613.28, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (9, NULL, GETDATE(), 387.58, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (10, NULL, GETDATE(), 1350.11, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (11, 12, GETDATE(), 23234.36, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (12, NULL, GETDATE(), 179.01, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (13, NULL, GETDATE(), 3794.69, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (14, 15, GETDATE(), 14674.21, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (15, NULL, GETDATE(), 432.38, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (16, NULL, GETDATE(), 3153.4, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (17, 18, GETDATE(), 18872.7, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (18, NULL, GETDATE(), 463.2, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (19, NULL, GETDATE(), 1554.87, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (20, 1, GETDATE(), 9720.91, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (21, NULL, GETDATE(), 102.61, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (22, NULL, GETDATE(), 3430.49, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (23, 4, GETDATE(), 9538.47, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (24, NULL, GETDATE(), 320.5, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (25, NULL, GETDATE(), 3458.47, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (26, 7, GETDATE(), 8849.36, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (27, NULL, GETDATE(), 171.38, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (28, NULL, GETDATE(), 4827.36, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (29, 10, GETDATE(), 20221.15, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (30, NULL, GETDATE(), 470.55, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (31, NULL, GETDATE(), 3804.51, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (32, 13, GETDATE(), 15649.25, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (33, NULL, GETDATE(), 167.17, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (34, NULL, GETDATE(), 1748.18, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (35, 16, GETDATE(), 21901.44, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (36, NULL, GETDATE(), 383.11, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (37, NULL, GETDATE(), 3987.32, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (38, 19, GETDATE(), 14377.75, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (39, NULL, GETDATE(), 191.59, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (40, NULL, GETDATE(), 2614.23, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (41, 2, GETDATE(), 13683.67, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (42, NULL, GETDATE(), 141.98, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (43, NULL, GETDATE(), 3124.69, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (44, 5, GETDATE(), 18537.2, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (45, NULL, GETDATE(), 122.27, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (46, NULL, GETDATE(), 2376.2, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (47, 8, GETDATE(), 11028.49, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (48, NULL, GETDATE(), 296.08, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (49, NULL, GETDATE(), 3943.06, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (50, 11, GETDATE(), 13644.32, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (51, NULL, GETDATE(), 135.07, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (52, NULL, GETDATE(), 1340.24, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (53, 14, GETDATE(), 6515.76, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (54, NULL, GETDATE(), 227.92, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (55, NULL, GETDATE(), 2582.97, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (56, 17, GETDATE(), 20157.89, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (57, NULL, GETDATE(), 405.18, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (58, NULL, GETDATE(), 2961.13, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (59, 20, GETDATE(), 9014.76, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (60, NULL, GETDATE(), 396.27, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (61, NULL, GETDATE(), 3845.73, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (62, 3, GETDATE(), 16914.05, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (63, NULL, GETDATE(), 240.39, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (64, NULL, GETDATE(), 991.36, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (65, 6, GETDATE(), 9641.64, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (66, NULL, GETDATE(), 281.75, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (67, NULL, GETDATE(), 4551.94, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (68, 9, GETDATE(), 12047.93, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (69, NULL, GETDATE(), 122.8, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (70, NULL, GETDATE(), 3561.58, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (71, 12, GETDATE(), 17182.24, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (72, NULL, GETDATE(), 466.63, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (73, NULL, GETDATE(), 3449.83, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (74, 15, GETDATE(), 11031.88, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (75, NULL, GETDATE(), 327.52, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (76, NULL, GETDATE(), 3324.9, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (77, 18, GETDATE(), 7052.43, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (78, NULL, GETDATE(), 205.29, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (79, NULL, GETDATE(), 3558.88, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (80, 1, GETDATE(), 10115.83, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (81, NULL, GETDATE(), 431.57, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (82, NULL, GETDATE(), 3807.98, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (83, 4, GETDATE(), 13247.1, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (84, NULL, GETDATE(), 465.03, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (85, NULL, GETDATE(), 4543.64, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (86, 7, GETDATE(), 19608.27, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (87, NULL, GETDATE(), 418.24, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (88, NULL, GETDATE(), 3207.13, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (89, 10, GETDATE(), 20886.28, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (90, NULL, GETDATE(), 336.59, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (91, NULL, GETDATE(), 4787.84, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (92, 13, GETDATE(), 16228.7, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (93, NULL, GETDATE(), 250.93, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (94, NULL, GETDATE(), 1701.18, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (95, 16, GETDATE(), 22667.96, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (96, NULL, GETDATE(), 223.7, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (97, NULL, GETDATE(), 640.11, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (98, 19, GETDATE(), 21778.2, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (99, NULL, GETDATE(), 238.05, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (100, NULL, GETDATE(), 2159.91, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (101, 2, GETDATE(), 14260.37, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (102, NULL, GETDATE(), 285.52, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (103, NULL, GETDATE(), 4869.79, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (104, 5, GETDATE(), 12966.2, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (105, NULL, GETDATE(), 154.28, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (106, NULL, GETDATE(), 2742.83, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (107, 8, GETDATE(), 11185.84, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (108, NULL, GETDATE(), 377.0, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (109, NULL, GETDATE(), 1868.62, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (110, 11, GETDATE(), 20958.92, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (111, NULL, GETDATE(), 455.08, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (112, NULL, GETDATE(), 2317.17, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (113, 14, GETDATE(), 17845.07, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (114, NULL, GETDATE(), 413.0, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (115, NULL, GETDATE(), 3434.85, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (116, 17, GETDATE(), 8618.05, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (117, NULL, GETDATE(), 211.96, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (118, NULL, GETDATE(), 1196.31, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (119, 20, GETDATE(), 20049.95, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (120, NULL, GETDATE(), 141.96, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (121, NULL, GETDATE(), 1175.28, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (122, 3, GETDATE(), 7478.0, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (123, NULL, GETDATE(), 317.3, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (124, NULL, GETDATE(), 1562.15, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (125, 6, GETDATE(), 21148.98, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (126, NULL, GETDATE(), 316.11, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (127, NULL, GETDATE(), 3115.36, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (128, 9, GETDATE(), 18840.8, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (129, NULL, GETDATE(), 266.9, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (130, NULL, GETDATE(), 811.37, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (131, 12, GETDATE(), 11526.11, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (132, NULL, GETDATE(), 473.85, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (133, NULL, GETDATE(), 4235.97, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (134, 15, GETDATE(), 11035.45, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (135, NULL, GETDATE(), 202.24, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (136, NULL, GETDATE(), 2946.52, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (137, 18, GETDATE(), 11874.62, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (138, NULL, GETDATE(), 425.88, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (139, NULL, GETDATE(), 2886.18, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (140, 1, GETDATE(), 5316.75, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (141, NULL, GETDATE(), 108.67, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (142, NULL, GETDATE(), 2720.84, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (143, 4, GETDATE(), 14148.61, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (144, NULL, GETDATE(), 442.36, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (145, NULL, GETDATE(), 2357.25, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (146, 7, GETDATE(), 7099.46, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (147, NULL, GETDATE(), 230.13, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (148, NULL, GETDATE(), 3929.54, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (149, 10, GETDATE(), 8814.98, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (150, NULL, GETDATE(), 201.45, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (151, NULL, GETDATE(), 1612.12, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (152, 13, GETDATE(), 11640.47, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (153, NULL, GETDATE(), 116.65, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (154, NULL, GETDATE(), 1345.73, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (155, 16, GETDATE(), 16001.37, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (156, NULL, GETDATE(), 256.77, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (157, NULL, GETDATE(), 588.45, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (158, 19, GETDATE(), 18735.1, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (159, NULL, GETDATE(), 287.87, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (160, NULL, GETDATE(), 4367.07, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (161, 2, GETDATE(), 6430.76, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (162, NULL, GETDATE(), 460.67, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (163, NULL, GETDATE(), 2285.07, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (164, 5, GETDATE(), 11924.42, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (165, NULL, GETDATE(), 257.64, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (166, NULL, GETDATE(), 1351.52, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (167, 8, GETDATE(), 21387.24, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (168, NULL, GETDATE(), 291.18, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (169, NULL, GETDATE(), 4568.57, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (170, 11, GETDATE(), 8461.42, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (171, NULL, GETDATE(), 417.74, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (172, NULL, GETDATE(), 666.93, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (173, 14, GETDATE(), 21002.45, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (174, NULL, GETDATE(), 277.61, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (175, NULL, GETDATE(), 1327.51, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (176, 17, GETDATE(), 17409.48, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (177, NULL, GETDATE(), 357.69, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (178, NULL, GETDATE(), 638.2, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (179, 20, GETDATE(), 5079.81, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (180, NULL, GETDATE(), 218.71, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (181, NULL, GETDATE(), 3347.2, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (182, 3, GETDATE(), 5346.98, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (183, NULL, GETDATE(), 454.74, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (184, NULL, GETDATE(), 1607.91, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (185, 6, GETDATE(), 5682.51, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (186, NULL, GETDATE(), 116.65, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (187, NULL, GETDATE(), 720.16, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (188, 9, GETDATE(), 10264.97, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (189, NULL, GETDATE(), 284.54, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (190, NULL, GETDATE(), 1909.9, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (191, 12, GETDATE(), 20011.52, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (192, NULL, GETDATE(), 326.94, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (193, NULL, GETDATE(), 3476.33, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (194, 15, GETDATE(), 10149.73, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (195, NULL, GETDATE(), 262.19, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (196, NULL, GETDATE(), 3230.61, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (197, 18, GETDATE(), 18640.34, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (198, NULL, GETDATE(), 490.61, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (199, NULL, GETDATE(), 4546.75, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (200, 1, GETDATE(), 16128.62, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (201, NULL, GETDATE(), 125.41, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (202, NULL, GETDATE(), 1092.76, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (203, 4, GETDATE(), 21811.39, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (204, NULL, GETDATE(), 236.1, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (205, NULL, GETDATE(), 2626.72, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (206, 7, GETDATE(), 7113.96, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (207, NULL, GETDATE(), 306.05, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (208, NULL, GETDATE(), 1875.15, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (209, 10, GETDATE(), 9509.48, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (210, NULL, GETDATE(), 346.26, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (211, NULL, GETDATE(), 4900.03, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (212, 13, GETDATE(), 14055.99, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (213, NULL, GETDATE(), 477.57, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (214, NULL, GETDATE(), 1404.48, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (215, 16, GETDATE(), 21798.04, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (216, NULL, GETDATE(), 473.58, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (217, NULL, GETDATE(), 2418.99, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (218, 19, GETDATE(), 10218.39, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (219, NULL, GETDATE(), 284.02, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (220, NULL, GETDATE(), 1771.06, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (221, 2, GETDATE(), 19885.86, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (222, NULL, GETDATE(), 309.57, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (223, NULL, GETDATE(), 1553.48, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (224, 5, GETDATE(), 5834.55, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (225, NULL, GETDATE(), 221.44, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (226, NULL, GETDATE(), 2873.43, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (227, 8, GETDATE(), 22133.44, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (228, NULL, GETDATE(), 162.2, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (229, NULL, GETDATE(), 2427.14, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (230, 11, GETDATE(), 5551.25, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (231, NULL, GETDATE(), 284.51, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (232, NULL, GETDATE(), 2763.8, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (233, 14, GETDATE(), 17304.5, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (234, NULL, GETDATE(), 459.42, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (235, NULL, GETDATE(), 736.11, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (236, 17, GETDATE(), 22027.63, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (237, NULL, GETDATE(), 346.9, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (238, NULL, GETDATE(), 4179.27, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (239, 20, GETDATE(), 21248.11, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (240, NULL, GETDATE(), 147.04, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (241, NULL, GETDATE(), 3609.02, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (242, 3, GETDATE(), 15236.72, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (243, NULL, GETDATE(), 227.78, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (244, NULL, GETDATE(), 2358.15, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (245, 6, GETDATE(), 16233.3, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (246, NULL, GETDATE(), 356.81, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (247, NULL, GETDATE(), 3221.32, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (248, 9, GETDATE(), 20447.65, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (249, NULL, GETDATE(), 143.17, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (250, NULL, GETDATE(), 694.75, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (251, 12, GETDATE(), 22071.9, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (252, NULL, GETDATE(), 383.76, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (253, NULL, GETDATE(), 1302.51, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (254, 15, GETDATE(), 5643.13, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (255, NULL, GETDATE(), 122.24, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (256, NULL, GETDATE(), 897.87, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (257, 18, GETDATE(), 9784.67, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (258, NULL, GETDATE(), 176.6, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (259, NULL, GETDATE(), 2677.44, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (260, 1, GETDATE(), 10378.07, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (261, NULL, GETDATE(), 476.48, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (262, NULL, GETDATE(), 1600.69, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (263, 4, GETDATE(), 16179.78, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (264, NULL, GETDATE(), 420.59, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (265, NULL, GETDATE(), 3075.77, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (266, 7, GETDATE(), 12929.15, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (267, NULL, GETDATE(), 261.74, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (268, NULL, GETDATE(), 2612.65, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (269, 10, GETDATE(), 20867.29, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (270, NULL, GETDATE(), 167.19, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (271, NULL, GETDATE(), 1162.8, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (272, 13, GETDATE(), 16772.88, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (273, NULL, GETDATE(), 390.35, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (274, NULL, GETDATE(), 3303.13, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (275, 16, GETDATE(), 7409.26, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (276, NULL, GETDATE(), 241.23, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (277, NULL, GETDATE(), 4359.19, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (278, 19, GETDATE(), 15254.89, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (279, NULL, GETDATE(), 144.96, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (280, NULL, GETDATE(), 1082.78, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (281, 2, GETDATE(), 24455.52, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (282, NULL, GETDATE(), 424.36, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (283, NULL, GETDATE(), 2720.3, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (284, 5, GETDATE(), 23414.55, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (285, NULL, GETDATE(), 448.6, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (286, NULL, GETDATE(), 1333.86, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (287, 8, GETDATE(), 11444.53, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (288, NULL, GETDATE(), 156.83, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (289, NULL, GETDATE(), 2151.68, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (290, 11, GETDATE(), 23248.39, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (291, NULL, GETDATE(), 194.85, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (292, NULL, GETDATE(), 2874.34, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (293, 14, GETDATE(), 22959.32, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (294, NULL, GETDATE(), 428.86, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (295, NULL, GETDATE(), 4224.84, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (296, 17, GETDATE(), 6770.72, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (297, NULL, GETDATE(), 488.01, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (298, NULL, GETDATE(), 1823.85, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (299, 20, GETDATE(), 19970.26, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (300, NULL, GETDATE(), 117.13, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (301, NULL, GETDATE(), 1755.47, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (302, 3, GETDATE(), 18109.32, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (303, NULL, GETDATE(), 327.51, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (304, NULL, GETDATE(), 730.37, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (305, 6, GETDATE(), 17193.75, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (306, NULL, GETDATE(), 224.98, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (307, NULL, GETDATE(), 3733.16, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (308, 9, GETDATE(), 17371.06, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (309, NULL, GETDATE(), 214.65, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (310, NULL, GETDATE(), 3418.89, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (311, 12, GETDATE(), 23477.97, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (312, NULL, GETDATE(), 171.93, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (313, NULL, GETDATE(), 1891.43, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (314, 15, GETDATE(), 18947.82, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (315, NULL, GETDATE(), 353.32, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (316, NULL, GETDATE(), 4952.72, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (317, 18, GETDATE(), 22480.19, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (318, NULL, GETDATE(), 442.47, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (319, NULL, GETDATE(), 1793.29, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (320, 1, GETDATE(), 20265.1, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (321, NULL, GETDATE(), 486.22, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (322, NULL, GETDATE(), 1155.04, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (323, 4, GETDATE(), 15424.56, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (324, NULL, GETDATE(), 182.06, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (325, NULL, GETDATE(), 929.49, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (326, 7, GETDATE(), 8063.26, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (327, NULL, GETDATE(), 352.78, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (328, NULL, GETDATE(), 1910.27, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (329, 10, GETDATE(), 10340.37, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (330, NULL, GETDATE(), 438.07, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (331, NULL, GETDATE(), 851.63, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (332, 13, GETDATE(), 12902.54, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (333, NULL, GETDATE(), 168.74, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (334, NULL, GETDATE(), 2164.72, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (335, 16, GETDATE(), 14823.24, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (336, NULL, GETDATE(), 275.73, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (337, NULL, GETDATE(), 789.14, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (338, 19, GETDATE(), 12335.87, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (339, NULL, GETDATE(), 252.54, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (340, NULL, GETDATE(), 3859.74, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (341, 2, GETDATE(), 16597.59, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (342, NULL, GETDATE(), 318.82, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (343, NULL, GETDATE(), 1560.36, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (344, 5, GETDATE(), 15633.61, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (345, NULL, GETDATE(), 124.69, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (346, NULL, GETDATE(), 3594.91, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (347, 8, GETDATE(), 18852.61, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (348, NULL, GETDATE(), 476.82, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (349, NULL, GETDATE(), 3088.63, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (350, 11, GETDATE(), 9342.82, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (351, NULL, GETDATE(), 135.95, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (352, NULL, GETDATE(), 1181.09, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (353, 14, GETDATE(), 11662.26, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (354, NULL, GETDATE(), 163.95, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (355, NULL, GETDATE(), 2148.05, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (356, 17, GETDATE(), 24966.64, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (357, NULL, GETDATE(), 344.53, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (358, NULL, GETDATE(), 4791.64, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (359, 20, GETDATE(), 6752.45, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (360, NULL, GETDATE(), 499.95, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (361, NULL, GETDATE(), 4978.95, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (362, 3, GETDATE(), 19421.61, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (363, NULL, GETDATE(), 120.39, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (364, NULL, GETDATE(), 1763.55, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (365, 6, GETDATE(), 20484.21, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (366, NULL, GETDATE(), 477.12, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (367, NULL, GETDATE(), 2213.22, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (368, 9, GETDATE(), 13855.68, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (369, NULL, GETDATE(), 199.07, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (370, NULL, GETDATE(), 1856.04, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (371, 12, GETDATE(), 12030.08, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (372, NULL, GETDATE(), 429.57, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (373, NULL, GETDATE(), 4020.25, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (374, 15, GETDATE(), 6537.32, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (375, NULL, GETDATE(), 184.21, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (376, NULL, GETDATE(), 3148.25, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (377, 18, GETDATE(), 9522.67, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (378, NULL, GETDATE(), 165.87, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (379, NULL, GETDATE(), 1435.11, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (380, 1, GETDATE(), 5099.45, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (381, NULL, GETDATE(), 238.69, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (382, NULL, GETDATE(), 927.67, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (383, 4, GETDATE(), 23531.78, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (384, NULL, GETDATE(), 242.0, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (385, NULL, GETDATE(), 4235.31, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (386, 7, GETDATE(), 24903.74, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (387, NULL, GETDATE(), 101.78, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (388, NULL, GETDATE(), 1042.12, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (389, 10, GETDATE(), 11796.05, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (390, NULL, GETDATE(), 483.21, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (391, NULL, GETDATE(), 1657.85, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (392, 13, GETDATE(), 11143.58, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (393, NULL, GETDATE(), 267.37, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (394, NULL, GETDATE(), 3897.07, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (395, 16, GETDATE(), 8873.89, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (396, NULL, GETDATE(), 177.25, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (397, NULL, GETDATE(), 4334.05, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (398, 19, GETDATE(), 10358.03, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (399, NULL, GETDATE(), 490.5, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (400, NULL, GETDATE(), 4400.52, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (401, 2, GETDATE(), 17045.67, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (402, NULL, GETDATE(), 267.56, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (403, NULL, GETDATE(), 1408.45, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (404, 5, GETDATE(), 24671.87, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (405, NULL, GETDATE(), 338.67, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (406, NULL, GETDATE(), 2177.34, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (407, 8, GETDATE(), 9936.08, 'Employer Remittance');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (408, NULL, GETDATE(), 369.46, 'M-Pesa');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (409, NULL, GETDATE(), 4261.98, 'Bank Transfer');
INSERT INTO Contributions (MemberID, EmployerID, ContributionDate, Amount, PaymentMethod) VALUES (410, 11, GETDATE(), 8875.27, 'Employer Remittance');
